### ISSUE TITLE
Question about finetuned T5.

### ISSUE THREAD

**Issue by guozix** [CVMI-Lab/SyntheticData#1]
Thanks for the instructive work.
I'm trying to use the language model to generate some of the desired texts.  And I'm wondering if the parameter of finetuned T5 are open sourced? I read the paper "CommonGen" but can't find the released T5 parameters after finetuning.

**Comment by RuiFeiHe** [comment]
Hi,

Thanks for your attention! You can refer to this link (https://huggingface.co/mrm8488/t5-base-finetuned-common_gen) and follow the instructions and usage from here (https://github.com/gagan3012/keytotext).
