### ISSUE TITLE
Question about freezing BN.

### ISSUE THREAD

**Issue by guozix** [CVMI-Lab/SyntheticData#2]
Hello! I observe that freezing BN brings non-trivial performance gains according to the ablation study.
In principle, the parameters from pretrained backbone are freezed already.
So I'm wondering where the mentioned BN layer belongs. Does it refer to BN layers belonging to the Classifier Tuning module?

**Comment by RuiFeiHe** [comment]
Hi,
The BN layers refer to those in the pretrained backbone.
